// <auto-generated />
namespace JavaNovaPosthaBot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class CreateReminder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateReminder));
        
        string IMigrationMetadata.Id
        {
            get { return "201909251142076_CreateReminder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
