Select o.ORDERID, od.ORDERDETAILID, pr.PRODUCTID, pr.MODEL, od.COUNTPRODUCT, od.PRICE From SHOP.ORDERS o
Join SHOP.ORDERDETAILS od On o.ORDERID = od.IDORDER
Join SHOP.PRODUCTS pr On od.IDPRODUCT = pr.PRODUCTID
Where o.ORDERID = 12


delete from SHOP.ORDERDETAILS where ORDERDETAILID = 40